"""Final verdict computation: consolidate residuals for the A/B/C call."""
from fractions import Fraction
import mpmath as mp
mp.mp.dps = 50

print("SUMMARY OF RESIDUALS")
print("="*70)
print("Task 1 (CF spine): 53,84,22,306,665 are EXACT convergent p/q values,")
print("  shared tail across log2(3)/beta/1/beta/log2(3)-1 (all same CF tail,")
print("  shifted by integer/reciprocal transforms). Zero residual -- exact.")
print()
print("Task 2 (exponent 6):")
print("  Our regression on C=10 curve m=7..12: b_fit=0.0630991, matches")
print("  published 0.063099 to rel error 1.3e-6 (rounding-limited).")
print("  Best (convergent,exponent): (84,53)^6, err vs regression = 9.9e-5 (0.0099%)")
print("  Next-best alternative (306,485)^6 or (665,1054)^6: err ~3.3e-4 (30x worse)")
print("  Continuous best-fit exponent for 84/53: k*=5.99978 (0.00022 from integer 6,")
print("    tightest of all convergents tested -- 65/41 gives k*=5.996, 485/306")
print("    gives k*=5.9993). This IS a genuine near-miss to integer 6, but 6 does")
print("    NOT arise from any independent CF invariant (partial quotient sum=11,")
print("    a6=1, convergent index=6 is circular/definitional). VERDICT: exponent 6")
print("    is an empirical near-integer coincidence tied SPECIFICALLY to convergent")
print("    84/53, not derived from CF structure by an independent formula.")
print()
print("Task 3 (9/4 search): NOT FOUND. No convergent or semiconvergent of")
print("  log2(3), beta, 1/beta, or log2(3)-1 equals 9/4 exactly, in 15 CF terms")
print("  (denominators up to 10-digit scale). Closest: semiconvergent 7/3 of")
print("  1/beta at rel error 3.7%; convergent 53/22 itself is 7.07% off 9/4.")
print("  No mediant of adjacent log2(3) convergents equals 9/4 (checked k=0..11).")
print("  This is FAR outside CF-convergent tolerance (true convergents match to")
print("  ~1/q^2, i.e. <<1%; 3.7%-7% errors are not convergent-quality matches).")
print()
print("Task 4 (jump-rate drift): order file's own floor(9n/4)+2 +-1 claim FAILS")
print("  to hold for k=3..8 (actual diffs 2-3, not <=1). Using the order file's")
print("  OWN claimed jump set, empirical rate n_k/k DECREASES monotonically for")
print("  k=5..8: 2.2 -> 2.167 -> 2.143 -> 2.125, moving AWAY from both 9/4=2.25")
print("  and 53/22=2.409 (regression slope over all 8 = 1.964, below both).")
print("  Using an unbiased empirical definition (top-8 deltas by size, dropping")
print("  boundary n=1), rate oscillates 2.25-2.4 without clean monotonic drift")
print("  either way, and the single LARGEST delta in the whole table (55, at")
print("  n=18) was excluded from the order file's claimed set despite exceeding")
print("  every claimed jump's delta. VERDICT: no clean convergence to 53/22;")
print("  data is noisy/short (18 points) and marginally favors stable-near-9/4")
print("  over drift-to-53/22, but neither is a confident call at this sample size.")
