#!/usr/bin/env python3
"""
Task 3: candidate invariants for hole-depth, per prime.
Exact integer computation of multiplicative orders, h_p, and related quantities.
"""
import json

def mult_order(a, p):
    a = a % p
    if a == 0:
        return None
    x = a
    k = 1
    while x != 1:
        x = (x * a) % p
        k += 1
        if k > p:  # safety, shouldn't happen for a coprime to p
            return None
    return k

def main():
    d = json.load(open("orbit_stationary.json"))
    rows = []
    for p_str, rec in d["primes"].items():
        p = int(p_str)
        ord2 = mult_order(2, p)
        ord3 = mult_order(3, p)
        h_p = rec["trig_res"]
        rel_hole = rec["hole"] / rec["pred_1_over_p"]
        # candidate invariants
        same_order = (ord2 == ord3)
        ratio_ord = ord2 / ord3 if ord3 else None
        # is 2 a primitive root mod p? (ord2 == p-1)
        prim2 = (ord2 == p - 1)
        prim3 = (ord3 == p - 1)
        # order of 2 within <3> or relation: is 2 in subgroup generated by 3?
        # check by brute force: is 2 = 3^k mod p for some k?
        in_sub3 = None
        if ord3:
            powers3 = set()
            x = 1
            for _ in range(ord3):
                powers3.add(x)
                x = (x * 3) % p
            in_sub3 = (2 % p) in powers3
        # h_p relation: is h_p a power of 2? of 3? index of h_p in cyclic group mod p (if p prime, group is cyclic order p-1)
        # find a primitive root g mod p, compute discrete logs of 2,3,h_p base g
        g = None
        for cand in range(2, p):
            if mult_order(cand, p) == p - 1:
                g = cand
                break
        def dlog(a, g, p):
            x = 1
            for k in range(p - 1):
                if x == a % p:
                    return k
                x = (x * g) % p
            return None
        dlog2 = dlog(2, g, p) if g else None
        dlog3 = dlog(3, g, p) if g else None
        dlogh = dlog(h_p, g, p) if g else None
        rows.append(dict(p=p, ord2=ord2, ord3=ord3, same_order=same_order,
                          prim2=prim2, prim3=prim3, in_sub3=in_sub3,
                          h_p=h_p, g=g, dlog2=dlog2, dlog3=dlog3, dlogh=dlogh,
                          rel_hole=rel_hole, hole=rec["hole"]))
        print(f"p={p:3d} ord2={ord2:3d} ord3={ord3:3d} same={str(same_order):5s} "
              f"prim2={str(prim2):5s} prim3={str(prim3):5s} in_sub3={str(in_sub3):5s} "
              f"h_p={h_p:3d} g={g:3d} dlog2={dlog2:3d} dlog3={dlog3:3d} dlogh={dlogh} "
              f"rel_hole={rel_hole:+.4f}")

    with open("invariants.json", "w") as f:
        json.dump(rows, f, indent=2)

if __name__ == "__main__":
    main()
